### ISSUE TITLE
return_valid_floor_in_range is highly inefficient

### ISSUE THREAD

**Issue by remove32** [TheSwain/Fulpstation#304]
## Round ID:
[6412](https://scrubby.melonmesa.com/round/6412)

## Testmerges:
None

## Reproduction:
![image](https://user-images.githubusercontent.com/27014495/77852475-85b49100-71a4-11ea-84e6-e4c489800089.png)
When determining efficiency using the profile, it's recommended to compare the Self CPU to the number of Calls. In the screenshot, the ratio of Self CPU to Calls for /proc/return_valid_floor_in_range is pretty bad. This proc is defined in code\FulpstationCode\fulp_procs.dm and is used in the code for beefmen's phobetor tears. @TheSwain if we get some time we should investigate how to better optimize this.

**Comment by LemonInTheDark** [comment]
What in god's name 
![image](https://user-images.githubusercontent.com/58055496/77993038-2194e880-72dc-11ea-90f6-5daa5c084573.png)

There's a few things you could do here that might help, but I'm willing to bet this call in beefmen code is the source of your pain.

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/78007181-857ed780-7303-11ea-87bf-6132cd6c6532.png)

**Comment by remove32** [comment]
> 
> 
> What in god's name
> ![image](https://user-images.githubusercontent.com/58055496/77993038-2194e880-72dc-11ea-90f6-5daa5c084573.png)
> 
> There's a few things you could do here that might help, but I'm willing to bet this call in beefmen code is the source of your pain.

yep kinda figured tbh. will look into optimizing this or temporarily removing the phobetor tear feature

**Comment by TheSwain** [comment]
So heads up - the Beefman brain trauma is based on the "bluespace prophet" trauma. It's almost a direct copy paste, except for some functionality differences.

@ATH1909 The suggestions in that screencap either don't apply or won't help. For example, putting the minimum range check earlier is more costly, not less. Always do the least costly checks with the highest likelihood to remove elements first. The min range check involves using range() a second time.

Because it's a costly operation, I'm going to sacrifice function for efficiency and have the tears appear less often by letting the game just pick randomly from locations, rather than sorting through a modified list of all valids. If the location is invalid, it will try again but much more quickly.

**Comment by ATH1909** [comment]
> Because it's a costly operation, I'm going to sacrifice function for efficiency and have the tears appear less often by letting the game just pick randomly from locations, rather than sorting through a modified list of all valids. If the location is invalid, it will try again but much more quickly.

Maybe do checks on up to 10 random tiles within a 20x20 area to see if they're both safe and 6 or more tiles away from you, and if none are found, just don't make any phoebetor tears for that tick?

**Comment by TheSwain** [comment]
That's what I'm doing, more or less.

**Comment by TheSwain** [comment]
Okay, if we're only picking a random location, say, 20 tiles away, but rejecting any tile closer than 6 (min range), then instead of picking ANY tile within 20 tiles of the character, i;m going to pick a random direction and check 6 tiles away from the character instead. Then anything within 14 tiles of the new location would do nearly the same thing. 

This would reduce the tiles in the range() check from 20 to 14, and completely eliminate the second range() check for minimum range.

**Comment by LemonInTheDark** [comment]
you should also prob use get_dist() here rather then range()
`		if (minRange > 0 && (locate(T) in range(A, minRange)))`

**Comment by TheSwain** [comment]
Quite true @LemonInTheDark 

I'm finding a way that cuts the need for any minimum range checks, but I'll make that change to the older code in case it ever comes back

**Comment by TheSwain** [comment]
Okay, brought this up with Windar and I think I have a new plan.

The original proc was meant to GUARANTEE you find a tile when you ask for one. This feature is not important enough to need that. We just want something that generally finds a location some distance away from you.

Instead of getting all tiles in an area and picking a valid one, we could instead just randomly wander X tiles away from the player and record all tiles we've run across. We would create a list of valid tiles starting at minimum distance D1 until we reach maximum distance D2. Then randomly pick from those.

This would almost definitely resolve all the overhead issues with the floor-finder proc.
